# pretrained_model_path: None
# train_image_path: C:\inz\train_data\loon\train
# validation_image_path: C:\inz\train_data\loon\validation
# class_names_file_path: C:\inz\train_data\loon\train\classes.txt
# input_rows: 128
# input_cols: 512
# input_channels: 3
# model_name: loon
# model_type: n1p3
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\square_set
# validation_image_path: C:\inz\train_data\square_set
# class_names_file_path: C:\inz\train_data\square_set\classes.txt
# input_rows: 512
# input_cols: 512
# input_channels: 1
# model_name: square
# model_type: n1p2
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\circle_regtangle\train
# validation_image_path: C:\inz\train_data\circle_regtangle\validation
# class_names_file_path: C:\inz\train_data\circle_regtangle\train\classes.txt
# input_rows: 512
# input_cols: 512
# input_channels: 3
# model_name: cr
# model_type: s1p2
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\lp_detection\train
# validation_image_path: C:\inz\train_data\lp_detection\validation
# class_names_file_path: C:\inz\train_data\lp_detection\train\classes.txt
# input_rows: 384
# input_cols: 640
# input_channels: 1
# model_name: lpd
# model_type: s1p3
# optimizer: sgd
# lr_policy: step

pretrained_model_path: None
train_image_path: C:\inz\train_data\lcd_new\lcd_b2\train
validation_image_path: C:\inz\train_data\lcd_new\lcd_b2\validation
class_names_file_path: C:\inz\train_data\lcd_new\lcd_b2\train\classes.txt
input_rows: 96
input_cols: 192
input_channels: 1
model_name: lcd_b2
model_type: n1p3
optimizer: sgd
lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\lp_in_car\train
# validation_image_path: C:\inz\train_data\lp_in_car\validation
# class_names_file_path: C:\inz\train_data\lp_in_car\train\classes.txt
# input_rows: 256
# input_cols: 256
# input_channels: 1
# model_name: lp_in_car
# model_type: n1p3
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\kaggle\car_detection\train
# validation_image_path: C:\inz\train_data\kaggle\car_detection\validation
# class_names_file_path: C:\inz\train_data\kaggle\car_detection\train\classes.txt
# input_rows: 256
# input_cols: 512
# input_channels: 1
# model_name: kaggle_car
# model_type: s1p3
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train
# validation_image_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\validation
# class_names_file_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train\classes.txt
# input_rows: 384
# input_cols: 640
# input_channels: 1
# model_name: lp_car_with_normal
# model_type: n1p3
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: None
# train_image_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train\normal
# validation_image_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\validation\normal
# class_names_file_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train\normal\classes.txt
# input_rows: 384
# input_cols: 640
# input_channels: 1
# model_name: normal_12cls
# model_type: s1p2
# optimizer: sgd
# lr_policy: step

lr: 0.001
l2: 0.0005
obj_alpha: 0.25
obj_gamma: 1.0
cls_alpha: 0.5
cls_gamma: 1.0
warm_up: 0.5
momentum: 0.9
smoothing: 0.0
decay_step: 0.1
ignore_scale: 0.0
batch_size: 4
iterations: 30000
curriculum_iterations: 0
training_view: False
map_checkpoint: False
map_checkpoint_interval: 1000
multi_classification_at_same_box: False
