# pretrained_model_path: None
# train_image_path: C:\inz\train_data\loon\train
# validation_image_path: C:\inz\train_data\loon\validation
# class_names_file_path: C:\inz\train_data\loon\train\classes.txt
# input_rows: 128
# input_cols: 512
# input_channels: 3
# model_name: loon
# model_type: n1p3
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_name: square
# model_type: n1p3
# input_shape: (512 512 1)
# train_image_path: rC:\inz\train_data\square_set
# validation_image_path: rC:\inz\train_data\square_set
# class_names_file_path: rC:\inz\train_data\square_set\classes.txt
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_name: cr
# model_type: s1p2
# input_shape: (512 512 3)
# train_image_path: rC:\inz\train_data\circle_regtangle\train
# validation_image_path: rC:\inz\train_data\circle_regtangle\validation
# class_names_file_path: rC:\inz\train_data\circle_regtangle\train\classes.txt
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_name: lpd
# model_type: s1p3
# input_shape: (352 640 1)
# train_image_path: rC:\inz\train_data\lp_detection\train
# validation_image_path: rC:\inz\train_data\lp_detection\validation
# class_names_file_path: rC:\inz\train_data\lp_detection\train\classes.txt
# optimizer: adam
# lr_policy: step

# pretrained_model_path: r
# model_name: lcdw
# model_type: n1p2
# input_shape: (96 192 1)
# train_image_path: rC:\inz\train_data\lcd_white\train
# validation_image_path: rC:\inz\train_data\lcd_white\validation
# class_names_file_path: rC:\inz\train_data\lcd_white\train\classes.txt
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_name: lpincar
# model_type: n1p3
# input_shape: (256 256 1)
# train_image_path: rC:\inz\train_data\lp_in_car\train
# validation_image_path: rC:\inz\train_data\lp_in_car\validation
# class_names_file_path: rC:\inz\train_data\lp_in_car\train\classes.txt
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_type: s1p3
# model_name: kagglecar
# input_shape: (256 512 1)
# train_image_path: rC:\inz\train_data\kaggle\car_detection\train
# validation_image_path: rC:\inz\train_data\kaggle\car_detection\validation
# class_names_file_path: rC:\inz\train_data\kaggle\car_detection\train\classes.txt
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_type: n1p3
# model_name: lp_car_sub
# input_shape: (256 512 1)
# train_image_path: rC:\inz\train_data\lp_car_detection_sub\train
# validation_image_path: rC:\inz\train_data\lp_car_detection_sub\validation
# class_names_file_path: rC:\inz\train_data\lp_car_detection_sub\train\classes.txt
# optimizer: sgd
# lr_policy: step

# pretrained_model_path: r
# model_type: n1p3
# model_name: lp_car_with_normal
# input_shape: (352 640 1)
# train_image_path: rC:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train
# validation_image_path: rC:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\validation
# class_names_file_path: rC:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train\classes.txt
# optimizer: sgd
# lr_policy: step

pretrained_model_path: None
train_image_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train\normal
validation_image_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\validation\normal
class_names_file_path: C:\inz\train_data\lp_car_with_normal_640x384_keep_ratio_resized\train\normal\classes.txt
input_rows: 384
input_cols: 640
input_channels: 1
model_name: normal_12cls
model_type: s1p2
optimizer: sgd
lr_policy: step

lr: 0.001
l2: 0.0005
alpha: 0.25
gamma: 2.0
warm_up: 0.5
momentum: 0.9
smoothing: 0.0
decay_step: 0.1
heatmap_scale: 0.4
batch_size: 4
iterations: 700000
curriculum_iterations: 0
training_view: False
map_checkpoint: False
map_checkpoint_interval: 10000
multi_classification_at_same_box: False
