devices: [0]
pretrained_model_path: null
train_data_path: /train_data/coco/train
validation_data_path: /train_data/coco/validation
class_names_file_path: /train_data/coco/train/classes.txt
input_rows: 416
input_cols: 416
input_channels: 3
model_name: coco
model_type: m
activation: leaky
p6_model: false
optimizer: sgd
lr_policy: step
lr: 0.001
lrf: 0.05
l2: 0.0005
dropout: 0.0
cls_balance: 0.0
box_weight: 5.0
aug_noise: 0.0
aug_scale: 0.5
aug_mosaic: 0.2
aug_h_flip: false
aug_v_flip: false
aug_contrast: 0.3
aug_brightness: 0.3
aug_snowstorm: 0.0
warm_up: 0.5
momentum: 0.9
smoothing: 0.0
ignore_scale: 0.0
va_iou_threshold: 1.0
batch_size: 4
max_q_size: 1024
iterations: 1000000
checkpoint_interval: 0
show_progress: false
treat_unknown_as_class: false
multi_classification_at_same_box: false
