pretrained_model_path: None
train_image_path: /train_data/coco/train
validation_image_path: /train_data/coco/validation
class_names_file_path: /train_data/coco/train/classes.txt
input_rows: 416
input_cols: 416
input_channels: 1
model_name: coco
model_type: m1p2
optimizer: sgd
lr_policy: step
lr: 0.001
l2: 0.0005
dropout: 0.1
obj_alpha: 0.25
obj_gamma: 1.0
cls_alpha: 0.5
cls_gamma: 1.0
aug_scale: 0.9
aug_contrast: 0.3
aug_brightness: 0.3
warm_up: 0.5
momentum: 0.9
smoothing: 0.1
decay_step: 0.1
ignore_scale: 0.1
batch_size: 4
num_workers: 8
iterations: 1000000
map_checkpoint_interval: 0
training_view: False
multi_classification_at_same_box: False
